### ISSUE TITLE
Totems lose their abilities

### ISSUE THREAD

**Issue by iMMy-Vortex** [zardoru/vrxcl#132]
When a player moves out of range from their totems, they stop working.
Tested on Earth Totem. Gives AC  2x dmg at lvl 10 when player is near totem, stops working when player moves away.

**Comment by Vortex-Quake2** [comment]
This is an old bug, but I checked it out anyway. Totem range is defined in lua as:
```
-- Totems
TOTEM_MAX_RANGE                          = 512
```

So yes, totems have a maximum range, and the effect only lasts while you are in range. It's working as intended unless I'm missing something.
