### ISSUE TITLE
No boss spawning in map "zpinv2"

### ISSUE THREAD

**Issue by Enemy-123** [zardoru/vrxcl#174]

**Comment by Vortex-Quake2** [comment]
I'm not sure this is a game/code issue. The map designer or whomever created the .ent file placed the monster spawning entities in small areas with low ceilings, so the boss won't fit. In fact, nothing big will fit, including tanks. I'll leave the Issue open though in case we want to make a hack for this map and maps like it. One possibility would be to try spawning large monsters on a nearby navi or nearby area, but really the most elegant "fix" would be to fix the .ent monster spawn entity placements.
