### ISSUE TITLE
Laser destroyed by a respawning player wont restore the count ( stuck in 6/6 )

### ISSUE THREAD

**Issue by Enemy-123** [zardoru/vrxcl#179]
only can fix using laser remove

**Comment by Vortex-Quake2** [comment]
Can't reproduce this. Can you clarify how this is done?

**Comment by Enemy-123** [comment]
During invasion, in this map makoinv I used lasers behind the spawns, and then a player respawned and insta deleted my lasers, the count was stuck on 6/6 and i couldn't put any more lasers, until I typed laser remove

I was thinking that probably this "auto remove" could be disabled during pvm/invasion, or probably ctf too.

Example of lasers:
![quake102](https://user-images.githubusercontent.com/78334500/214131992-618ce2b7-06fd-42f7-bdb5-fada23eb7f73.jpg)


Evidence of that day lol
![quake078](https://user-images.githubusercontent.com/78334500/214132549-b8deac14-8380-4230-86bd-d71f643da2ab.jpg)

**Comment by Vortex-Quake2** [comment]
Fixed. Also gave lasers a boost against non-clients.
