### ISSUE TITLE
Cacodemon morph can't be pulled by monster brain

### ISSUE THREAD

**Issue by Enemy-123** [zardoru/vrxcl#180]

**Comment by Vortex-Quake2** [comment]
Tested cacodemon against a level 5 monster brain and level 5 poltergeist brain: Pull was working; however, it wasn't strong enough, and the cacodemon was able to escape. Repeated the same test at level 10, and the brain's pull was strong enough to prevent the cacodemon's escape. Conclusion: Working as intended.
