### ISSUE TITLE
Runes Labeling

### ISSUE THREAD

**Issue by iMMy-Vortex** [zardoru/vrxcl#22]
Runes picked up do not have a name or label and appear as blank in the inventory

**Comment by Tomekchan** [comment]
![quake025](https://user-images.githubusercontent.com/67880977/87397011-0cc43280-c5f7-11ea-9bc8-ff7058e09b50.jpg)

**Comment by zardoru** [comment]
![image](https://user-images.githubusercontent.com/391382/87600719-09e24400-c6c2-11ea-864e-a88c0e9fb964.png)
I can't really reproduce this one either... Someone on linux please debug if possible.
