### ISSUE TITLE
Armory Pages

### ISSUE THREAD

**Issue by iMMy-Vortex** [zardoru/vrxcl#24]
Next page / Prev Page disappears on the last armory page so you have to press [ or ] several times to goto the menu selection. Not really a big bug

**Comment by Tomekchan** [comment]
I've noticed this one too.

**Comment by xcessive30** [comment]
Rune pages also bugged. Above issue can be resolved by setting default cursor position if I'm not mistaken? 
![quake014](https://user-images.githubusercontent.com/55841915/87371402-44799e80-c553-11ea-98ac-e2220e54318c.jpg)
![quake016](https://user-images.githubusercontent.com/55841915/87371403-44799e80-c553-11ea-9236-102c3681c96e.jpg)

**Comment by zardoru** [comment]
I can't reproduce it. I think it's got to do with a stale armoryitems.dat.

**Comment by zardoru** [comment]
Yeah it was a stale armoryitems.dat. Also should land on the Next item.
