### ISSUE TITLE
Selling a unique combo rune 

### ISSUE THREAD

**Issue by iMMy-Vortex** [zardoru/vrxcl#35]
Selling a unique combo rune does not go in the armory

**Comment by iMMy-Vortex** [comment]
Combo Runes with less than 40 points will reach the armory, ones with 40 points or higher dont

**Comment by zardoru** [comment]
This happens because the price of the unique is less than the price of the combo rune. If someone's got an idea of what to do in this case...

**Comment by zardoru** [comment]
For reference, price for uniques is 150k.

**Comment by iMMy-Vortex** [comment]
Actually,

I tried selling the unique combos to an empty armory. There were no runes in the armory. Only a few of the unique combos sold went to the armory, the rest just didnt display.

Salim Balolia
Creative Director
salim@busybeetools.com


------Original Mail------
